### ISSUE TITLE
Too verbose logging?

### ISSUE THREAD

**Issue by Halama** [keboola/ex-generic-mock-server#1]
Pro data https://github.com/keboola/app-generic-faker loguje:

![image](https://user-images.githubusercontent.com/903531/33835967-6320776e-de88-11e7-804c-2103575a925a.png)

https://github.com/keboola/ex-generic-mock-server/blob/a4676b72a4b9730ef4ed16de063330272bf8aeb9/src/AppBundle/Controller/ApiController.php#L135

**Comment by odinuv** [comment]
Fixed in a2a7704
